_target_: model_merging.data.dataset.load_dataset
name: Cars
preprocess_fn: ???
ft_epochs: 35
hf_dataset: 
  _target_: model_merging.data.dataset.load_hf_dataset_filtered
  path: tanganke/stanford_cars
