_target_: model_merging.data.dataset.load_dataset
name: EMNIST
ft_epochs: 2
preprocess_fn: ???
hf_dataset: 
  _target_: model_merging.data.dataset.load_hf_dataset_filtered
  path: tanganke/emnist_mnist
