_target_: model_merging.data.dataset.load_dataset
name: FashionMNIST
ft_epochs: 5
preprocess_fn: ???
hf_dataset: 
  _target_: model_merging.data.dataset.load_hf_dataset_filtered
  path: zalando-datasets/fashion_mnist
