_target_: model_merging.data.dataset.load_dataset
name: Flowers102
ft_epochs: 147
preprocess_fn: ???
hf_dataset: 
  _target_: model_merging.data.dataset.load_hf_dataset_filtered
  path: dpdl-benchmark/oxford_flowers102
