_target_: model_merging.data.dataset.load_dataset
name: Food101
ft_epochs: 4 
preprocess_fn: ???
hf_dataset: 
  _target_: model_merging.data.dataset.load_hf_dataset_filtered
  path: ethz/food101
split_map:
  train: train
  test: validation