_target_: model_merging.data.dataset.load_dataset
name: OxfordIIITPet
ft_epochs: 82
preprocess_fn: ???
hf_dataset: 
  _target_: model_merging.data.dataset.load_hf_dataset_filtered
  path: timm/oxford-iiit-pet
