_target_: model_merging.merger.dual_merging.DualMerger

alpha: null  # If provided, overrides optimal_alphas lookup

optimal_alphas:
  ViT-B-16:
    '8': 1.4
    '14': 1.3
    '20': 1.4
  ViT-B-32:
    '8': 1.4
    '14': 1.5
    '20': 1.6
  ViT-L-14:
    '8': 2.9
    '14': 2.6
    '20': 3.0

svd_path: null  # Set to a path to enable SVD caching
#svd_compress_factor: 16.5
svd_compress_factor: null
device: ${device}
model_name: ${nn.encoder.model_name}
